pull_request_rules:
  - name: Automatic merge
    description: Merge PRs that are ready
    conditions:
      - label = automerge
    actions:
      merge:
        method: rebase
  - name: Label Dependabot PRs
    conditions:
      - author=dependabot[bot]
    actions:
      label:
        add:
          - automerge
